// <auto-generated />
using System;
using ControleDeIncidente.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleDeIncidente.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190926152210_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleDeIncidente.Models.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdIncidente");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("ControleDeIncidente.Models.Interacao", b =>
                {
                    b.Property<int>("IdInteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataInteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IncidenteIdIncidente")
                        .HasColumnType("int");

                    b.HasKey("IdInteracao");

                    b.HasIndex("IncidenteIdIncidente");

                    b.ToTable("Interacoes");
                });

            modelBuilder.Entity("ControleDeIncidente.Models.Interacao", b =>
                {
                    b.HasOne("ControleDeIncidente.Models.Incidente", null)
                        .WithMany("Interacoes")
                        .HasForeignKey("IncidenteIdIncidente");
                });
#pragma warning restore 612, 618
        }
    }
}
